### ISSUE TITLE
connection failing

### ISSUE THREAD

**Issue by yellowkid21** [d4az/hack-gmail#4]
Name The File Path (For Password List) => /home/kali/hack-gmail/rockyou.txt
Traceback (most recent call last):
  File "hack-gmail.py", line 44, in <module>
    smtpserver.login(user, password)
  File "/usr/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 635, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib/python3.8/smtplib.py", line 425, in docmd
    return self.getreply()
  File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by ebadfd** [comment]
hi that happens because when you just did a password attack to the G-Mail account google will block that account temporary from login and stuff. The script is working perfectly and please try after some time. it should work. 

thanks.

**Comment by ebadfd** [comment]
![Screenshot_2021-02-10_15_48_44](https://user-images.githubusercontent.com/66930150/107571257-aea11180-6c10-11eb-8844-8aae113030e1.png)
